# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 927c44f4eb6ed729eaccd3359d5c0dd7816983ff10ddd0d6df796b41a217cb46c253e88c438cd57d6a8ab04dec818ac6518c2d3f844357312df7083d8e6c26b3

test:
  secret_key_base: 6ee07f04fe5da5445d3887d49e2746459c50fecb2dd63dd6b139aab233d250d0b981e14261c25d387c4b1b6a8683fc27383bd03f33304dabf707b82568f29cd1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
